import type { Metadata } from "next";

import "lenis/dist/lenis.css";

import { LenisProvider } from "@/components/lenis-provider";
import { RevealObserver } from "@/components/reveal-observer";

import "./globals.css";

export const metadata: Metadata = {
  title: "Language Skills",
  description:
    "Skills, prompts, and language-specific rules to improve the code generated by AI agents across Python, Java, Rust, C++, TypeScript, React, R, PHP, and Ruby.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body>
        <LenisProvider />
        <RevealObserver />
        {children}
      </body>
    </html>
  );
}
